-- Modelo de acceso acordado: aplicación colaborativa mediante enlace.
-- Los visitantes anónimos pueden consultar, crear y actualizar.
-- DELETE queda reservado a service_role / administración de Supabase.

begin;

alter table public.desarrollos enable row level security;
alter table public.desarrolladores enable row level security;
alter table public.desarrollo_dev enable row level security;
alter table public.soportes_mantenimiento enable row level security;

revoke delete on table public.desarrollos from public, anon, authenticated;
revoke delete on table public.desarrolladores from public, anon, authenticated;
revoke delete on table public.soportes_mantenimiento from public, anon, authenticated;

grant select, insert, update on table public.desarrollos to anon;
grant select, insert, update on table public.desarrolladores to anon;
grant select, insert, update on table public.desarrollo_dev to anon;
grant select, insert, update on table public.soportes_mantenimiento to anon;
grant delete on table public.desarrollo_dev to anon;
grant usage, select on all sequences in schema public to anon;

drop policy if exists "public_select_desarrollos" on public.desarrollos;
drop policy if exists "public_insert_desarrollos" on public.desarrollos;
drop policy if exists "public_update_desarrollos" on public.desarrollos;
create policy "public_select_desarrollos"
on public.desarrollos for select to anon using (true);
create policy "public_insert_desarrollos"
on public.desarrollos for insert to anon with check (true);
create policy "public_update_desarrollos"
on public.desarrollos for update to anon using (true) with check (true);

drop policy if exists "public_select_desarrolladores" on public.desarrolladores;
drop policy if exists "public_insert_desarrolladores" on public.desarrolladores;
drop policy if exists "public_update_desarrolladores" on public.desarrolladores;
create policy "public_select_desarrolladores"
on public.desarrolladores for select to anon using (true);
create policy "public_insert_desarrolladores"
on public.desarrolladores for insert to anon with check (true);
create policy "public_update_desarrolladores"
on public.desarrolladores for update to anon using (true) with check (true);

drop policy if exists "public_select_desarrollo_dev" on public.desarrollo_dev;
drop policy if exists "public_insert_desarrollo_dev" on public.desarrollo_dev;
drop policy if exists "public_update_desarrollo_dev" on public.desarrollo_dev;
drop policy if exists "public_delete_desarrollo_dev" on public.desarrollo_dev;
create policy "public_select_desarrollo_dev"
on public.desarrollo_dev for select to anon using (true);
create policy "public_insert_desarrollo_dev"
on public.desarrollo_dev for insert to anon with check (true);
create policy "public_update_desarrollo_dev"
on public.desarrollo_dev for update to anon using (true) with check (true);
create policy "public_delete_desarrollo_dev"
on public.desarrollo_dev for delete to anon using (true);

drop policy if exists "public_select_soportes" on public.soportes_mantenimiento;
drop policy if exists "public_insert_soportes" on public.soportes_mantenimiento;
drop policy if exists "public_update_soportes" on public.soportes_mantenimiento;
create policy "public_select_soportes"
on public.soportes_mantenimiento for select to anon using (true);
create policy "public_insert_soportes"
on public.soportes_mantenimiento for insert to anon with check (true);
create policy "public_update_soportes"
on public.soportes_mantenimiento for update to anon using (true) with check (true);

-- El código histórico usó dos variantes del mismo estado.
update public.desarrollos
set estado = 'En Proceso'
where estado in ('En proceso', 'En proceso ');

-- Historial administrativo. No identifica personas porque no hay cuentas,
-- pero permite recuperar qué cambió y cuándo.
create table if not exists public.backlog_audit_log (
    id bigint generated by default as identity primary key,
    table_name text not null,
    operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
    row_id text,
    old_data jsonb,
    new_data jsonb,
    changed_at timestamptz not null default now(),
    database_role text not null default coalesce(
        nullif(current_setting('request.jwt.claim.role', true), ''),
        current_user
    )
);

alter table public.backlog_audit_log enable row level security;
revoke all on table public.backlog_audit_log from public, anon, authenticated;
grant select on table public.backlog_audit_log to service_role;

create or replace function public.capture_backlog_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.backlog_audit_log (
        table_name,
        operation,
        row_id,
        old_data,
        new_data
    ) values (
        tg_table_name,
        tg_op,
        coalesce(to_jsonb(new)->>'id', to_jsonb(old)->>'id'),
        case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) end,
        case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) end
    );
    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

revoke all on function public.capture_backlog_change() from public;

drop trigger if exists audit_desarrollos on public.desarrollos;
create trigger audit_desarrollos
after insert or update or delete on public.desarrollos
for each row execute function public.capture_backlog_change();

drop trigger if exists audit_desarrolladores on public.desarrolladores;
create trigger audit_desarrolladores
after insert or update or delete on public.desarrolladores
for each row execute function public.capture_backlog_change();

drop trigger if exists audit_desarrollo_dev on public.desarrollo_dev;
create trigger audit_desarrollo_dev
after insert or update or delete on public.desarrollo_dev
for each row execute function public.capture_backlog_change();

drop trigger if exists audit_soportes on public.soportes_mantenimiento;
create trigger audit_soportes
after insert or update or delete on public.soportes_mantenimiento
for each row execute function public.capture_backlog_change();

commit;
